### ISSUE TITLE
gem release

### ISSUE THREAD

**Issue by yegor256** [juusaw/amp-jekyll#1]
Would be great if you release this as a gem. If you need help, check this out: http://www.yegor256.com/2014/08/26/publish-to-rubygems.html

**Comment by juusaw** [comment]
If that'd be any help, I could definitely do that. I've never released a ruby gem before and there's one thing that I'm not sure how to do. 

The plugin needs the html template to generate the pages and that template has to be in the specific folder in the Jekyll project. Is there a way to do this with a gem? If not, one would need to manually copy the file to the directory and keep it updated (as the standard may change).

 I can release the `rb` files as a gem if that's any help. It would then be the user's job to add the html template.

**Comment by tosbourn** [comment]
@juusaw one way you can handle that is have a feature of the gem be to generate the html file in the correct place.

That way as specs change you can have the latest and greatest be generated.

**Comment by juusaw** [comment]
Hi @tosbourn !

Initially generating the file sounds like a good idea.

I'll have to take a better look  at how Ruby gems generally handle situations like this before getting the release out.

**Comment by juusaw** [comment]
The gem has been released!

I ended up not adding the html file initially. This can be changed in future versions if it seems like a feature that people would find helpful.

https://rubygems.org/gems/amp-jekyll
