### ISSUE TITLE
amp folder not accessible

### ISSUE THREAD

**Issue by sreevisakh** [juusaw/amp-jekyll#12]
I have configure the plugin and set amp as the `ampdir` .  amp files are generating in my local but when I deploy them to github pages amp pages gives 404.

**Comment by juusaw** [comment]
Hi,

Unfortunately, GitHub pages [supports only a small list of Jekyll plugins](https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/). The only way to use any other plugins, like amp-jekyll, is to build the site locally and commit only the `_site` directory as a static site.
