### ISSUE TITLE
Convert *.rb to *.js

### ISSUE THREAD

**Issue by cikal** [juusaw/amp-jekyll#17]
I can't use this plugin, because github forbid plugin on free account. Can u convert this plugin to JS file??

**Comment by juusaw** [comment]
Unfortunately, that's not possible. The AMP pages must be generated on server, not client-side. Thus the Javascript would not work as intended.

One alternative is to build the site locally and only commit the generated site to your Github Pages repositoty. Alternately you might look into other hosting options that allow running Jekyll plugins.
