### ISSUE TITLE
Ignores posts with a permalink

### ISSUE THREAD

**Issue by JamieMason** [juusaw/amp-jekyll#27]
Thanks for this great plugin.

I've noticed that if I give my post `permalink: /somewhere` front matter that it is no longer picked up by amp-jekyll, is there anything I can do to workaround this please?

**Comment by juusaw** [comment]
Hi,

I managed to get this sorted out. It seems that the page generation failed silently when the AMP post had the same permalink as the original post copied over to it. Deleting the attribute from the page fixed this. Commit ad341b2d6bf3bd138a679e844ac76afb60fe94b does this.

I'll make a release soon with this fix included.

**Comment by juusaw** [comment]
Fixed in 1.0.2

**Comment by aav7fl** [comment]
@juusaw

Soo... this actually goes backwards for me. Like the opposite of what is happening in #29 , but I have narrowed it to this ticket/changes.

I was using a permalink with a different url, I was expecting my post (after update from `1.0.1`->`1.0.2`) to be `/amp/blog/2017/05/15/welcome-to-jekyll/`, but now it is `/amp/blog/2017/05/15/welcome-to-jekyll.html`.. 

My website links are supposed to be like `www.example.com/blog/2017/05/15/welcome-to-jekyll/` while my amp pages are supposed to be `www.example.com/amp/blog/2017/05/15/welcome-to-jekyll/`.  Is this not the way it is supposed to work? 

[Repo that I'm using it in](https://github.com/aav7fl/aav7fl.github.io/tree/cb3ae007e5be7054d7fcf967af5dbd46b365da38).
