### ISSUE TITLE
Plugin Not Working

### ISSUE THREAD

**Issue by mzaini30** [juusaw/amp-jekyll#35]
I tried all instructiions in README but plugin is still not working.

This is my blogpost: http://muhammadzaini.com/2017/10/03/bergeraklah-karena-ide-tak-bisa-didapatkan-dalam-sepi.html

AMP version (I wanna to): http://muhammadzaini.com/amp/2017/10/03/bergeraklah-karena-ide-tak-bisa-didapatkan-dalam-sepi.html

Repository: http://github.com/mzaini30/mzaini30.github.io

**Comment by tiste** [comment]
This is because github have not whitelisted the plugin on their [`gh-pages` stuff](https://github.com/github/pages-gem).
@juusaw did you push your plugin to github?

**Comment by juusaw** [comment]
I don't think the plugin is at a sufficiently mature state to be whitelisted by Github pages. It is definitely the goal but at the moment, the project is for example missing tests.

At the moment, to use the plugin with Github pages, you must locally generate the static HTML, including the AMP pages. The static content should then be pushed to the *.github.io repository.
