### ISSUE TITLE
Jekyll 4 Support

### ISSUE THREAD

**Issue by kylekirkby** [juusaw/amp-jekyll#48]
Hi,

We should add support for Jekyll 4 asap :) 

Kind regards,

Kyle

**Comment by guillemcanal** [comment]
Hey folks, do you have an ETA for this issue ? Thanks a lot.

Kind regards

**Comment by ndeverge** [comment]
Here is a pull request for Jekyll 4: https://github.com/juusaw/amp-jekyll/pull/49

**Comment by juusaw** [comment]
Pull request approved, merged and released. Version 1.0.3 of the gem should support Jekyll 4.
